### ISSUE TITLE
User defined date time format with delimiter

### ISSUE THREAD

**Issue by slaFFik** [Rarst/wpdatetime#1]
Woud be nice to have a getter for a date, that will format date/time like this (not a real code below) and will return `WpDateTime` instance.

```php
public function get_date_time( $date, $separator = ' @ ' ) {
    $format = get_option( 'date_format' ) . $separator . get_option( 'time_format' );
    $d = new WpDateTime( $date );

    return $d ? $d->format( $format ) : '';
}
```

**Comment by Rarst** [comment]
How is this different from just calling method directly?

    $date = WpDateTime::createFromFormat( get_option( 'date_format' ) . @ . get_option( 'time_format' ), $date );

Also could you please describe the use case? Generally parsing dates reliably is huge problem in first, more so with _arbitrary_ format containing who knows which parts.

**Comment by slaFFik** [comment]
I'm lazy and don't want to type `get_option( 'date_format' ) . ' @ ' . get_option( 'time_format' )` all the time.

**Comment by slaFFik** [comment]
There is no need to partse formats, we should stick to the one saved in WP core (those `date_/time_format`). So I would like to have a method that will be a wrapper around those WP built-in and user-defined date/time format that will return a `WpDateTime` object.

**Comment by Rarst** [comment]
define( 'MY_DATE_FORMAT', get_option( 'date_format' ) . '@' . get_option( 'time_format' ) );

?

I am not sure I follow. `createFromFormat()` is a _parser_ method. Giving it arbitrary format inputs would be... exceptionally unreliable.

Again, concrete use case might be in order? Where are your inputs coming from and what they are?

**Comment by slaFFik** [comment]
Isn't it a PHP 5.6+:
`define( 'MY_DATE_FORMAT', get_option( 'date_format' ) . ' @ ' . get_option( 'time_format' ) );`
If yes, not an option for my projects. Any way, I do not want to polute the global scope with that.

Why `get_option` is an arbitrary format? It's either saved or not. If not - ignore and return `null`, if yes - we have its format, predefined by WP.

**Comment by Rarst** [comment]
Defining constants isn't new... :)

Concrete example, please? I highly don't follow what is the purpose of this method would be.

**Comment by slaFFik** [comment]
The whole lib is about dates in WP, correct?
WP saves date/time format in DB. Requesting the full format is lots of chars typing, also validation (saved or not) is required before usage.
I request a new feature as a method, that will return a date in a saved WP date/time format (if saved) and will return `null` or `wp_error()` otherwise.

Usecase: shortcut around `get_option( 'date_format' ) . ' @ ' . get_option( 'time_format' )` usage with proper validation whether saved or not.

**Comment by slaFFik** [comment]
I have modified the initial pseudo-code snippet to better reflect what I actually meant. Previous version was completely wrong due to my mistake.

**Comment by Rarst** [comment]
Ok, here is about how I am slicing this:

**I want _this or that_ super specific format, based on respective WP options**

My take — define a constant with your specific desired format, use it.

**I want an easier way to access related WP options in API**

This is interesting, but I will need to think if there is possibly a reasonable API for it. As it is `get_option()` _is_ already quite laconic. It is a challenge to replace it with something that is more convenient, less typing, and easy to learn. Also options are _filterable_, so it's not a given that formats always have the same format between calls, even within a page load, so access would need to be dynamic as well as it's public code.

Unfortunately `date()` doesn't really have a concept of introducing custom placeholders to the format. Whatever it understands is hardcoded into PHP source. Anything that builds on top of it is handled by constants.

Closing for now, but will think on access to formats.

**Comment by Rarst** [comment]
Added `formatDate()` and `formatTime()` helper methods in version 0.2.
