### ISSUE TITLE
Please clearly define min PHP version

### ISSUE THREAD

**Issue by slaFFik** [Rarst/wpdatetime#2]
I assume PHP 5.4+, because of traits, but please specify more clearly in composer in `require` section.
Or in `readme.md`.

**Comment by Rarst** [comment]
Will do, just need to properly go/scan over code so that I am precise about it.

**Comment by slaFFik** [comment]
Will you do that for 0.2 release?

**Comment by Rarst** [comment]
Since I need to set up tooling for the scan I didn't do it for 0.2 today.

**Comment by slaFFik** [comment]
I see the commit.
Out of interest, I see only `[]` and traits that are 5.4+. But which things from 5.5 are you using?

**Comment by Rarst** [comment]
`DateTimeImmutable`

**Comment by slaFFik** [comment]
@Rarst 
It seems `5.5.10` is actually the minimum version, not `5.5.0`
http://php.net/manual/en/datetimezone.construct.php#refsect1-datetimezone.construct-changelog
`$create_timezone = new \DateTimeZone( 'UTC' );`

**Comment by Rarst** [comment]
Cheers, adjusted version in `composer.json` accordingly.
