### ISSUE TITLE
Date validation method

### ISSUE THREAD

**Issue by slaFFik** [Rarst/wpdatetime#3]
Would be helpful to be able to have a method to validate a date (is the date valid to be used in SQL or other similar scenarios). Similar to the code below:

```php
$default = new WpDateTime();
$d       = $default::createFromFormat( WpDateTime::MYSQL, $date );

return $d && $d->format( WpDateTime::MYSQL ) === $date;
```

**Comment by Rarst** [comment]
`createFromFormat(()` will return `false` on failure, generally all `DateTime` code I've seen uses that for validity check (alternately `new DateTime` will throw exception on failure).

I would guess that is the reason there is no dedicated validation method upstream, it doesn't seem necessary when validity is essentially inherent in return value already.

Does this make sense?

**Comment by slaFFik** [comment]
`createFromFormat` already not just creates, but validates during creation as well. So 
`false !== WpDateTime::createFromFormat( WpDateTime::MYSQL, $date);` 
should be sufficient.

**Comment by widoz** [comment]
Problem with the falsy approach is how do you do proper type int?
Imaging something like a class or a method that has a dependency on `WpDateTimeInterface` you'll get a `TypeError`. 

Would be more correct to throw an exception instead? The flow will benefit of that and the exception can be catch at high level.

**Comment by Rarst** [comment]
False on failure is consistent with static DateTime methods upstream.

WpDateTime supports PHP 5, so proper type hinting isn't available anyway.

WP doesn't really work well with exceptions, they aren't common and core itself won't bother trying to catch and handle exception, like modern frameworks tend to.

Would I use exceptions if this was a clean PHP 7 design? Probably. It's not though. :)

**Comment by widoz** [comment]
> WpDateTime supports PHP 5, so proper type hinting isn't available anyway.

Class type hint are allowed since PHP 5 so you can do something like `public function methodName(WpDateTime $wpDateTime){}`. (http://docs.php.net/manual/da/language.oop5.typehinting.php)

> WP doesn't really work well with exceptions

That's not a reason to me, throwing exceptions is the right way to do things in those circumstances IMO, if you are allowing to return a value different than the one expected you should throw an exception allowing the developer be aware of the problem and provide correct solution, this will favor type hint also as expressed above. If the factory is allowed to return two type values, which is the reason to have an interface? You're a breaking the contract that way.

**Comment by Rarst** [comment]
> Class type hint are allowed since PHP 5

Not for return types.

> That's not a reason to me, throwing exceptions is the right way to do things in those circumstances IMO

I am sorry, but I am not interested in debating rightness. This was designed the way it made sense me at the time, with what I considered sensible in upstream PHP and WP contexts.

As I mentioned in other thread this all is about to get deprecated by core functionality anyway, so I won't waste my time on any redesigns/rewrites regardless.

If you feel strongly about having a particular design to depend on — you are welcome to wrap or fork the code. :) Yay, open source.

**Comment by widoz** [comment]
K, thanks anyway
