### ISSUE TITLE
PhpUnit and DateTimeInterface can't be implemented by user classes Error

### ISSUE THREAD

**Issue by widoz** [Rarst/wpdatetime#6]
Let's say I have a class that has a dependency on `WpDateTimeInterface` and I want to test the constructor or a method that get passed the interface. 
If I want to test it I would create a test such as the following one

```
$dateTime = $this->createMock(WpDateTimeInterface::class);
$dateTimeFormat = 'Y-m-d';
$testee = new Testee($dateTime, $dateTimeFormat);

self::assertInstanceOf(Testee::class, $testee);
```

The test will always fail because of `PHP Fatal error:  DateTimeInterface can't be implemented by user classes` making practically impossible to create an unit test.

Due to this php problem would make sense to switch to an abstract class with abstract methods instead of rely on an interface that cannot be mocked?

Because the other way around would mean inject the implementation and that obviously will break the `D` of SOLID and also will not be possible to switch between mutable and immutable instances.

**Comment by Rarst** [comment]
You seem to be creating the mock exclusively for the sake of creating the mock. I see no problem whatsoever with using actual object in a test when it's simple and straighforward.

You are not testing how PHP type hinting works here.

In WP core (upcoming) this will not even have any inheritance, it would just be function returning native DateTimeImmutable object. It might have been better design for the lib, but it is what it is now and since it's about to be deprecated by core it's somewhat moot to mess with. :)

**Comment by widoz** [comment]
> You seem to be creating the mock exclusively for the sake of creating the mock.

The example was just to show how the error could be caused, let me propose a specific example.

```
$dateTime = $this->createMock(WpDateTimeInterface::class);
$dateTimeFormat = 'Y-m-d';
$testee = new Testee($dateTime, $dateTimeFormat);

$dateTime
    ->expects($this->once())
    ->method('formati18n')
    ->willReturn('2019-25-05')

$testee->testeeMethod();
```

Set expectations is a common thing in unit test and that's the problem I'll not able to set any expectation because the test will break right when I call `createMock`.

> In WP core (upcoming) this will not even have any inheritance, it would just be function returning native DateTimeImmutable object.

Sorry, I knew you wrote the project for WordPress but I was thinking could be used also as a composer library, so do you suggest that I have to wrap the logic within a function?

**Comment by Rarst** [comment]
> Sorry, I knew you wrote the project for WordPress but I was thinking could be used also as a composer library, so do you suggest that I have to wrap the logic within a function?

I don't see a point of using WordPress-specific code outside of WordPress context?.. :)

I mean that core will (likely) have `get_post_datetime()` function (see 
https://github.com/Rarst/wp-date/issues/4 ) and this whole lib will be made obsolete.

**Comment by widoz** [comment]
No I was not meant to use it outside, but if I have a class that would consume `WpDateTimeInterface` will be impossible to set expectations over the interface stub because isn't possible to create a mock for that.

> I mean that core will (likely) have get_post_datetime() function (see Rarst/wp-date#4 ) and this whole lib will be made obsolete.

Got it
